// Auto-generated by `ct types`
// DO NOT EDIT MANUALLY

export interface Deal {
  id: string;
  title: string;
  amount: number | null;
  currency: "CNY" | "USD" | "EUR" | "GBP" | "JPY" | null;
  stage: "prospecting" | "qualification" | "proposal" | "negotiation" | "closed_won" | "closed_lost" | null;
  probability: number | null;
  contact: string | null;
  company: string | null;
  owner_id: string | null;
  close_date: string | null;
  description: string | null;
  loss_reason: "no_budget" | "no_decision" | "lost_to_competitor" | "timing" | "lack_of_fit" | "other" | null;
  created_at: string;
  updated_at: string;
}
