[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.31.0"
ci = "github"
packages = ["raisfast"]
installers = ["shell", "powershell", "homebrew"]
targets = [
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "x86_64-pc-windows-msvc",
]
tap = "RaisFast/homebrew-tap"
publish-jobs = ["./publish-crates"]
merge-tasks = true
precise-builds = true
allow-dirty = ["ci"]
