//! Generated docreader proto bindings: client (+ server stubs for
//! in-process fakes in tests). Generated by `build.rs` from
//! `services/docreader/proto/docreader.proto`.

pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/docreader.rs"));
}

pub use pb::doc_reader_client::DocReaderClient;
// Server stubs: for in-process fakes (integration tests) — not used by the
// binary itself.
#[doc(hidden)]
pub use pb::doc_reader_server::{DocReader, DocReaderServer};
