use raisfast::event::Event;
use raisfast::export_type::collect_all;
use raisfast::services::media::{mime_to_ext, ALL_MEDIA_MIMES};

/// Extract job-type discriminant strings from the `Job` TS declaration.
///
/// The `Job` enum is a tagged union (`#[serde(tag = "type")]`), so ts-rs emits
/// `{ type: "send_welcome_email", payload: ... } | ...`. We parse out every
/// `type: "..."` and exclude the `custom` escape hatch (plugin-supplied).
///
/// This avoids hardcoding a parallel list — the `Job` enum is the single source
/// of truth; adding/removing a variant automatically updates this export.
fn emit_job_types(decls: &[(String, String)]) -> String {
    let job_decl = decls
        .iter()
        .find(|(name, _)| name == "Job")
        .map(|(_, decl)| decl.as_str())
        .unwrap_or("");

    let mut types: Vec<&str> = Vec::new();
    let mut rest = job_decl;
    while let Some(pos) = rest.find("\"type\":") {
        rest = &rest[pos + 7..];
        // skip whitespace then find the opening quote of the value
        let trimmed = rest.trim_start();
        if !trimmed.starts_with('"') {
            continue;
        }
        rest = &trimmed[1..];
        if let Some(end) = rest.find('"') {
            let tag = &rest[..end];
            if tag != "custom" {
                types.push(tag);
            }
            rest = &rest[end + 1..];
        } else {
            break;
        }
    }

    if types.is_empty() {
        return String::new();
    }

    let mut out = String::from("export const BuiltinJobTypes = [\n");
    for ty in &types {
        out.push_str(&format!("  \"{ty}\",\n"));
    }
    out.push_str("] as const;\n");
    out.push_str("export type BuiltinJobType = (typeof BuiltinJobTypes)[number];\n");
    out
}

fn emit_mime_ext() -> String {
    let mut out = String::from("export const MimeExt: Record<string, string> = {\n");
    for m in ALL_MEDIA_MIMES {
        out.push_str(&format!(
            "  \"{}\": \"{}\",\n",
            m.as_str(),
            mime_to_ext(m.as_str())
        ));
    }
    out.push_str("} as const;\n");
    out
}

/// Export all external event names from `Event::all_event_names()`.
///
/// The list is generated at compile time by the `EventMeta` derive macro from
/// `#[event(event_name = "...")]` attributes. This is the single source of truth —
/// the `Event` enum variants + `event_name` attributes determine which events appear.
fn emit_webhook_events() -> String {
    let events = Event::all_event_names();
    let mut out = String::from("export const EventNames = [\n");
    for ev in events {
        out.push_str(&format!("  \"{ev}\",\n"));
    }
    out.push_str("] as const;\n");
    out.push_str("export type EventName = (typeof EventNames)[number];\n");
    out
}

fn main() {
    let decls = collect_all();

    let mut out = String::from(
        "// Auto-generated by `cargo run --example export-types`\n// DO NOT EDIT MANUALLY\n\n",
    );

    for (_name, decl) in &decls {
        out.push_str(&format_type_decl(decl));
        out.push_str("\n\n");
    }

    out.push_str(&emit_job_types(&decls));
    out.push_str(&emit_webhook_events());
    out.push_str(&emit_mime_ext());

    let out_dir = "frontend/sdk/src/generated";
    std::fs::create_dir_all(out_dir).unwrap();
    let out_path = format!("{out_dir}/types.ts");
    std::fs::write(&out_path, out).unwrap();

    println!("Exported {} types to {}", decls.len(), out_path);
}

fn is_ts_identifier(s: &str) -> bool {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first == '$' || first.is_ascii_alphabetic())
        && chars.all(|c| c == '_' || c == '$' || c.is_ascii_alphanumeric())
}

fn format_type_decl(decl: &str) -> String {
    let decl = decl.trim();
    if !decl.starts_with("type ") {
        return decl.to_string();
    }
    let rest = &decl[5..];

    let eq_pos = match rest.find(" = ") {
        Some(p) => p,
        None => return format!("export type {rest};"),
    };

    let name_part = &rest[..eq_pos];
    let body_raw = rest[(eq_pos + 3)..].trim_end_matches(';').trim();

    let variants = split_top_level(body_raw, " | ");

    if variants.len() > 1 {
        let all_strings = variants.iter().all(|v: &&str| v.trim().starts_with('"'));
        if all_strings {
            let keys: Vec<String> = variants
                .iter()
                .map(|v: &&str| {
                    let v = v.trim();
                    let key = v.trim_matches('"');
                    let key = key.replace('-', "_");
                    let key = if is_ts_identifier(&key) {
                        key.to_string()
                    } else {
                        format!("\"{key}\"")
                    };
                    format!("  {key}: {v}")
                })
                .collect();
            let const_name = name_part.replace(" ", "");
            format!(
                "export const {const_name} = {{\n{}\n}} as const;\nexport type {const_name} = typeof {const_name}[keyof typeof {const_name}];",
                keys.join(",\n")
            )
        } else {
            let fmt: Vec<String> = variants
                .iter()
                .map(|v: &&str| {
                    let v = v.trim();
                    if v.starts_with('{') && v.ends_with('}') {
                        format_object(v, 2)
                    } else {
                        v.to_string()
                    }
                })
                .collect();
            format!("export type {name_part} =\n  | {};", fmt.join("\n  | "))
        }
    } else if body_raw.starts_with('{') {
        format!("export type {name_part} = {};", format_object(body_raw, 0))
    } else {
        format!("export type {name_part} = {body_raw};")
    }
}

fn format_object(obj: &str, base_indent: usize) -> String {
    let open = match obj.find('{') {
        Some(p) => p,
        None => return obj.to_string(),
    };
    let close = match obj.rfind('}') {
        Some(p) => p,
        None => return obj.to_string(),
    };
    if open >= close {
        return obj.to_string();
    }

    let inner = &obj[(open + 1)..close];
    let fields = split_top_level(inner, ",");

    let field_indent = " ".repeat(base_indent + 2);
    let close_indent = " ".repeat(base_indent);

    let mut result = String::from("{\n");
    for field in &fields {
        let field: &str = field.trim();
        if field.is_empty() {
            continue;
        }
        result.push_str(&reindent_block(field, &field_indent));
    }
    result.push_str(&close_indent);
    result.push('}');
    result
}

fn reindent_block(block: &str, indent: &str) -> String {
    let non_empty: Vec<&str> = block.lines().filter(|l| !l.trim().is_empty()).collect();

    if non_empty.is_empty() {
        return String::new();
    }

    let min_indent = non_empty
        .iter()
        .map(|l| l.len() - l.trim_start().len())
        .min()
        .unwrap_or(0);

    let mut result = String::new();
    for (idx, line) in non_empty.iter().enumerate() {
        let leading = line.len() - line.trim_start().len();
        let strip = leading.min(min_indent);
        result.push_str(indent);
        result.push_str(&line[strip..]);
        if idx == non_empty.len() - 1 {
            result.push(';');
        }
        result.push('\n');
    }
    result
}

fn split_top_level<'a>(s: &'a str, sep: &str) -> Vec<&'a str> {
    let mut result = Vec::new();
    let mut depth: i32 = 0;
    let mut angle_depth: i32 = 0;
    let mut in_line_comment = false;
    let mut in_block_comment = false;
    let mut start = 0;
    let bytes = s.as_bytes();
    let sep_len = sep.len();

    let mut i = 0;
    while i < s.len() {
        if !in_line_comment && !in_block_comment && i + 1 < s.len() {
            if bytes[i] == b'/' && bytes[i + 1] == b'/' {
                in_line_comment = true;
                i += 2;
                continue;
            }
            if bytes[i] == b'/' && bytes[i + 1] == b'*' {
                in_block_comment = true;
                i += 2;
                continue;
            }
        }

        if in_line_comment {
            if bytes[i] == b'\n' {
                in_line_comment = false;
            }
            i += 1;
            continue;
        }

        if in_block_comment {
            if i + 1 < s.len() && bytes[i] == b'*' && bytes[i + 1] == b'/' {
                in_block_comment = false;
                i += 2;
                continue;
            }
            i += 1;
            continue;
        }

        if bytes[i] == b'{' {
            depth += 1;
        } else if bytes[i] == b'}' {
            depth -= 1;
        } else if bytes[i] == b'<' {
            angle_depth += 1;
        } else if bytes[i] == b'>' {
            angle_depth -= 1;
        } else if depth == 0
            && angle_depth == 0
            && i + sep_len <= s.len()
            && &s[i..i + sep_len] == sep
        {
            result.push(&s[start..i]);
            i += sep_len;
            start = i;
            continue;
        }
        i += 1;
    }

    let remaining = &s[start..];
    if !remaining.trim().is_empty() {
        result.push(remaining);
    }
    result
}
