[content_type]
name = "some test"
singular = "some_test"
plural = "some_tests"
table = "some_tests"
implements = ["timestampable"]

[fields.title]
type = "text"
max_length = 255

[fields.bb]
type = "blob"
