//! Install materialization — the 8 ordered steps with compensation logging
//! (app-bundle.md §4.2).
//!
//! Discipline: the undo descriptor for every step is constructed in the same
//! place as the step itself and persisted via the progress sink immediately
//! after the step succeeds, so a kill -9 restart can replay compensation from
//! the DB. Undo semantics are shared with uninstall/self-heal through
//! [`crate::apps::uninstaller::run_undo`].

use std::path::{Path, PathBuf};
use std::sync::Arc;

use serde_json::Value;

use crate::apps::manifest::AppBundleManifest;
use crate::apps::model::{LogStep, UndoAction};
use crate::apps::package::{AppPackage, PluginPayload};
use crate::apps::seeder::{self, StepSink};
use crate::config::app::AppConfig;
use crate::content_type::ContentTypeRegistry;
use crate::content_type::repository::ContentRepository;
use crate::content_type::schema::ContentTypeSchema;
use crate::db::DbDriver;
use crate::errors::app_error::{AppError, AppResult};
use crate::integration::IntegrationPlane;
use crate::plugins::PluginManager;
use crate::protocols::ProtocolRegistry;
use crate::types::snowflake_id::SnowflakeId;

/// Handles the installer needs (all optional-late except pool/config/CT).
pub struct InstallCtx {
    pub pool: crate::db::Pool,
    pub config: Arc<AppConfig>,
    pub ct_registry: Arc<ContentTypeRegistry>,
    pub protocol_registry: Arc<ProtocolRegistry>,
    pub plugins: Option<Arc<PluginManager>>,
    pub plane: Option<Arc<IntegrationPlane>>,
}

/// The app row being installed.
pub struct InstallTarget {
    pub app_id: String,
    pub version: String,
    pub keep_data: bool,
}

/// Persists the compensation log after every step (kill -9 safety).
pub struct Progress {
    pool: crate::db::Pool,
    app_id: String,
    steps: Vec<LogStep>,
}

impl Progress {
    pub fn new(pool: crate::db::Pool, app_id: &str) -> Self {
        Self {
            pool,
            app_id: app_id.to_string(),
            steps: Vec::new(),
        }
    }

    /// Append + persist one step (undo generated by the caller, same place
    /// as the action — never after the fact).
    pub async fn commit_inherent(&mut self, mut step: LogStep) -> AppResult<()> {
        step.seq = self.steps.len() + 1;
        self.steps.push(step);
        let log = serde_json::json!({ "steps": self.steps });
        crate::apps::model::model::update_install_log(&self.pool, &self.app_id, &log).await
    }

    /// The accumulated steps (replay input for rollback / uninstall).
    #[must_use]
    pub fn steps(&self) -> &[LogStep] {
        &self.steps
    }
}

impl StepSink for Progress {
    async fn commit(&mut self, step: LogStep) -> AppResult<()> {
        self.commit_inherent(step).await
    }
}

/// Credential placeholders detected during materialization — the admin
/// "pending credentials" guide card input (§6.2 凭据行).
#[derive(Debug, Default)]
pub struct PendingCredentials {
    pub items: Vec<String>,
}

/// Run all 8 materialization steps in dependency order (§4.2). Returns the
/// pending-credential list; the caller folds it into `apps.options`.
pub async fn materialize(
    ctx: &InstallCtx,
    target: &InstallTarget,
    pkg: &AppPackage,
    progress: &mut Progress,
) -> AppResult<PendingCredentials> {
    let mut pending = PendingCredentials::default();

    step_permissions(ctx, target, &pkg.manifest, progress).await?;
    let ct_keys = step_content_types(ctx, target, pkg, progress).await?;
    let _ = ct_keys;
    let plugin_ids = step_plugins(ctx, target, pkg, progress).await?;
    step_crons(ctx, &plugin_ids, pkg, progress).await?;
    step_channels(ctx, target, pkg, progress, &mut pending).await?;
    step_api_clients(ctx, target, pkg, progress, &mut pending).await?;
    step_seeds(ctx, target, pkg, progress).await?;
    step_admin_pages(pkg, progress).await?;

    Ok(pending)
}

// ── Step 1: rbac namespace ──────────────────────────────────────────

async fn step_permissions(
    ctx: &InstallCtx,
    target: &InstallTarget,
    manifest: &AppBundleManifest,
    progress: &mut Progress,
) -> AppResult<()> {
    let pool = &ctx.pool;
    let role_name = target.app_id.clone();
    let (role_id, created) =
        match crate::models::rbac::find_role_id_by_name(pool, &role_name).await? {
            Some(id) => (id, false),
            None => {
                let role = crate::models::rbac::create_role(
                    pool,
                    &role_name,
                    Some(&format!("app namespace for {}", manifest.app.name)),
                )
                .await?;
                (role.id.0, true)
            }
        };

    for perm in &manifest.app.permissions {
        let subject = format!("{}:{}", target.app_id, perm);
        let sql = format!(
            "SELECT id FROM permissions WHERE role_id = {} AND subject = {}",
            crate::db::Driver::ph(1),
            crate::db::Driver::ph(2)
        );
        let exists: Option<(i64,)> = sqlx::query_as(crate::db::safe_sql(&sql))
            .bind(role_id)
            .bind(&subject)
            .fetch_optional(pool)
            .await?;
        if exists.is_some() {
            continue;
        }
        crate::models::rbac::insert_permission(
            pool,
            &crate::commands::CreatePermissionCmd {
                role_id: SnowflakeId(role_id),
                action: "allow".into(),
                subject,
                fields: None,
                conditions: None,
            },
        )
        .await?;
    }

    progress
        .commit_inherent(LogStep {
            seq: 0,
            step: "permissions".to_string(),
            detail: format!(
                "role '{role_name}' + {} namespaced permission(s)",
                manifest.app.permissions.len()
            ),
            undo: if created {
                UndoAction::DropRole {
                    role_id: role_id.to_string(),
                }
            } else {
                UndoAction::Noop
            },
            done: true,
        })
        .await?;
    Ok(())
}

// ── Step 2: content types ───────────────────────────────────────────

async fn step_content_types(
    ctx: &InstallCtx,
    target: &InstallTarget,
    pkg: &AppPackage,
    progress: &mut Progress,
) -> AppResult<Vec<String>> {
    let repo = ContentRepository::new(ctx.pool.clone());
    let reserved = ctx.config.builtins.reserved_route_segments();
    let protocol_names = ctx.protocol_registry.names();
    let mut keys = Vec::new();

    for payload in &pkg.content_types {
        let schema = &payload.schema;
        register_ct(ctx, schema, &reserved, &protocol_names).await?;
        repo.migrate(schema, &ctx.protocol_registry).await?;
        ensure_seed_key_column(&ctx.pool, schema).await?;

        crate::apps::model::model::insert_ct_ref(
            &ctx.pool,
            &crate::apps::model::AppCtRefRow {
                id: crate::utils::id::new_snowflake_id(),
                app_id: target.app_id.clone(),
                ct_table: schema.table.clone(),
                schema_toml: payload.toml_source.clone(),
                version: target.version.clone(),
                created_at: crate::utils::tz::now_utc(),
            },
        )
        .await?;

        let junctions = junction_tables(schema);
        progress
            .commit_inherent(LogStep {
                seq: 0,
                step: "content-types".to_string(),
                detail: format!(
                    "registered + migrated table '{}' (group '{}')",
                    schema.table, schema.group
                ),
                undo: UndoAction::UnregisterCt {
                    key: schema.registry_key(),
                },
                done: true,
            })
            .await?;
        progress
            .commit_inherent(LogStep {
                seq: 0,
                step: "content-types".to_string(),
                detail: format!("ct ref row for '{}'", schema.table),
                undo: UndoAction::DeleteCtRef {
                    table: schema.table.clone(),
                },
                done: true,
            })
            .await?;
        progress
            .commit_inherent(LogStep {
                seq: 0,
                step: "content-types".to_string(),
                detail: format!("table + junctions for '{}'", schema.table),
                undo: UndoAction::DropTable {
                    table: schema.table.clone(),
                    junctions,
                },
                done: true,
            })
            .await?;
        keys.push(schema.registry_key());
    }
    Ok(keys)
}

/// Register into the in-memory registry (host rules apply unchanged).
async fn register_ct(
    ctx: &InstallCtx,
    schema: &ContentTypeSchema,
    reserved: &[&str],
    protocol_names: &[&str],
) -> AppResult<()> {
    ctx.ct_registry
        .register(
            schema.clone(),
            &ctx.config.rule_engine,
            reserved,
            protocol_names,
            &ctx.protocol_registry,
        )
        .map_err(|e| {
            AppError::Internal(anyhow::anyhow!(
                "register content type '{}': {e}",
                schema.name
            ))
        })
}

/// Add the `seed_key` column + unique index (§6.1) to an app CT table.
/// Invariant: index exists iff we added the column (re-attached tables
/// already carry both).
async fn ensure_seed_key_column(
    pool: &crate::db::Pool,
    schema: &ContentTypeSchema,
) -> AppResult<()> {
    if crate::db::Driver::has_column(pool, &schema.table, "seed_key").await {
        return Ok(());
    }
    let alter = format!("ALTER TABLE {} ADD COLUMN seed_key TEXT", schema.table);
    sqlx::query(crate::db::safe_sql(&alter))
        .execute(pool)
        .await
        .map_err(|e| {
            AppError::Internal(anyhow::anyhow!("add seed_key to '{}': {e}", schema.table))
        })?;
    let idx_name = format!("idx_{}_seed_key_unique", schema.table);
    let idx = create_unique_index_sql(&idx_name, &schema.table, "seed_key");
    sqlx::query(crate::db::safe_sql(&idx))
        .execute(pool)
        .await
        .map_err(|e| {
            AppError::Internal(anyhow::anyhow!(
                "seed_key unique index on '{}': {e}",
                schema.table
            ))
        })?;
    Ok(())
}

/// MySQL lacks `CREATE UNIQUE INDEX IF NOT EXISTS`; we only create the index
/// right after adding the column, so the plain form is safe everywhere.
/// MySQL additionally requires a key length for TEXT columns (191 chars =
/// utf8mb4 index limit; seed keys are short strings).
fn create_unique_index_sql(name: &str, table: &str, column: &str) -> String {
    #[cfg(feature = "db-mysql")]
    {
        format!("CREATE UNIQUE INDEX {name} ON {table}({column}(191))")
    }
    #[cfg(not(feature = "db-mysql"))]
    {
        format!("CREATE UNIQUE INDEX {name} ON {table}({column})")
    }
}

/// Junction table names a CT generates (drop targets for uninstall).
fn junction_tables(schema: &ContentTypeSchema) -> Vec<String> {
    use crate::content_type::schema::RelationType;
    schema
        .fields
        .iter()
        .filter_map(|f| {
            let rel = f.relation.as_ref()?;
            matches!(
                rel.relation_type,
                RelationType::ManyToMany | RelationType::ManyWay
            )
            .then(|| {
                rel.through
                    .clone()
                    .unwrap_or_else(|| format!("{}_{}", schema.table, rel.target))
            })
        })
        .collect()
}

// ── Step 3: plugins ─────────────────────────────────────────────────

async fn step_plugins(
    ctx: &InstallCtx,
    target: &InstallTarget,
    pkg: &AppPackage,
    progress: &mut Progress,
) -> AppResult<Vec<String>> {
    let plugin_dir = plugin_root(ctx);
    let mut ids = Vec::new();
    for payload in &pkg.plugins {
        let name = payload.manifest.plugin.id.clone();
        let effective_id = pkg.manifest.plugin_id(&name);
        let dest = plugin_dir.join(&target.app_id).join(&name);
        materialize_plugin(payload, &dest, &effective_id)?;

        progress
            .commit_inherent(LogStep {
                seq: 0,
                step: "plugins".to_string(),
                detail: format!("materialized plugin '{effective_id}'"),
                undo: UndoAction::DeletePluginDir {
                    dir: dest.to_string_lossy().into_owned(),
                },
                done: true,
            })
            .await?;
        ids.push(effective_id);
    }
    Ok(ids)
}

fn plugin_root(ctx: &InstallCtx) -> PathBuf {
    Path::new(
        ctx.config
            .plugin_dir
            .as_deref()
            .unwrap_or("./extensions/plugins"),
    )
    .to_path_buf()
}

/// Copy the packaged plugin into `{plugin_dir}/{app_id}/{name}` rewriting the
/// manifest id to the namespaced `{app_id}/{name}` (§9).
fn materialize_plugin(payload: &PluginPayload, dest: &Path, effective_id: &str) -> AppResult<()> {
    if dest.exists() {
        std::fs::remove_dir_all(dest)
            .map_err(|e| AppError::Internal(anyhow::anyhow!("clean stale plugin dir: {e}")))?;
    }
    copy_dir(payload.dir.as_path(), dest)?;
    let manifest_path = dest.join("manifest.toml");
    let content = std::fs::read_to_string(&manifest_path)
        .map_err(|e| AppError::Internal(anyhow::anyhow!("read plugin manifest: {e}")))?;
    let mut doc: toml::Value = content
        .parse()
        .map_err(|e| AppError::Internal(anyhow::anyhow!("parse plugin manifest: {e}")))?;
    if let Some(plugin) = doc.get_mut("plugin").and_then(|p| p.as_table_mut()) {
        plugin.insert("id".into(), toml::Value::String(effective_id.to_string()));
    }
    let serialized = toml::to_string(&doc)
        .map_err(|e| AppError::Internal(anyhow::anyhow!("serialize manifest: {e}")))?;
    std::fs::write(&manifest_path, serialized)
        .map_err(|e| AppError::Internal(anyhow::anyhow!("write plugin manifest: {e}")))?;
    Ok(())
}

fn copy_dir(src: &Path, dest: &Path) -> AppResult<()> {
    std::fs::create_dir_all(dest)
        .map_err(|e| AppError::Internal(anyhow::anyhow!("create {dest:?}: {e}")))?;
    for entry in std::fs::read_dir(src)
        .map_err(|e| AppError::Internal(anyhow::anyhow!("read {src:?}: {e}")))?
    {
        let entry = entry.map_err(|e| AppError::Internal(anyhow::anyhow!("{e}")))?;
        let path = entry.path();
        let to = dest.join(entry.file_name());
        if path.is_dir() {
            copy_dir(&path, &to)?;
        } else {
            std::fs::copy(&path, &to)
                .map_err(|e| AppError::Internal(anyhow::anyhow!("copy {path:?}: {e}")))?;
        }
    }
    Ok(())
}

// ── Step 4: cron sync ───────────────────────────────────────────────

async fn step_crons(
    ctx: &InstallCtx,
    plugin_ids: &[String],
    pkg: &AppPackage,
    progress: &mut Progress,
) -> AppResult<()> {
    for payload in &pkg.plugins {
        let effective_id = pkg.manifest.plugin_id(&payload.manifest.plugin.id);
        if !plugin_ids.contains(&effective_id) {
            continue;
        }
        crate::worker::sync_plugin_crons(&ctx.pool, &effective_id, &payload.manifest.cron).await?;
        progress
            .commit_inherent(LogStep {
                seq: 0,
                step: "crons".to_string(),
                detail: format!(
                    "synced {} cron entr(y/ies) for '{effective_id}'",
                    payload.manifest.cron.len()
                ),
                undo: UndoAction::RemoveCrons {
                    plugin_id: effective_id.clone(),
                },
                done: true,
            })
            .await?;
    }
    Ok(())
}

// ── Step 5: channels ────────────────────────────────────────────────

async fn step_channels(
    ctx: &InstallCtx,
    _target: &InstallTarget,
    pkg: &AppPackage,
    progress: &mut Progress,
    pending: &mut PendingCredentials,
) -> AppResult<Vec<i64>> {
    let mut ids = Vec::new();
    let empty = serde_json::Map::new();
    for seed in &pkg.channel_seeds {
        let obj = seed.as_object().unwrap_or(&empty);
        let channel_key = obj
            .get("channel_key")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string();
        let now = crate::utils::tz::now_utc();
        let ch = crate::integration::channel::ItgChannel {
            id: crate::utils::id::new_snowflake_id(),
            tenant_id: crate::constants::DEFAULT_TENANT.to_string(),
            channel_key: channel_key.clone(),
            provider: str_field(obj, "provider"),
            display_name: str_field_or(obj, "display_name", &channel_key),
            mode: str_field(obj, "mode"),
            transport: str_field(obj, "transport"),
            framing: str_field(obj, "framing"),
            codec: str_field(obj, "codec"),
            endpoint: opt_str_field(obj, "endpoint"),
            verify_kind: str_field(obj, "verify_kind"),
            verify_config: obj.get("verify_config").cloned().filter(|v| !v.is_null()),
            credentials: None, // never ships in the package (§6.2)
            mapping: obj.get("mapping").cloned().filter(|v| !v.is_null()),
            normalizer_plugin: opt_str_field(obj, "normalizer_plugin"),
            pull_semantics: opt_str_field(obj, "pull_semantics"),
            pull_config: obj.get("pull_config").cloned().filter(|v| !v.is_null()),
            stream_config: obj.get("stream_config").cloned().filter(|v| !v.is_null()),
            ack_kind: str_field_or(obj, "ack_kind", "http-200"),
            redelivery_max: obj
                .get("redelivery_max")
                .and_then(Value::as_i64)
                .unwrap_or(5),
            backpressure: obj.get("backpressure").cloned().filter(|v| !v.is_null()),
            target_type: str_field(obj, "target_type"),
            route_extra: obj.get("route_extra").cloned().filter(|v| !v.is_null()),
            status: "idle".to_string(),
            last_error: None,
            lease_owner: None,
            enabled: false, // seeds land disabled; `enable` brings them up
            version: 1,
            shadow: false,
            created_at: now,
            updated_at: now,
        };
        crate::integration::channel::model::insert(&ctx.pool, &ch).await?;
        if channel_needs_credentials(&ch) {
            pending.items.push(format!("channel:{channel_key}"));
        }
        progress
            .commit_inherent(LogStep {
                seq: 0,
                step: "channels".to_string(),
                detail: format!("seeded channel '{channel_key}' (disabled)"),
                undo: UndoAction::DeleteChannel {
                    id: ch.id.0.to_string(),
                },
                done: true,
            })
            .await?;
        ids.push(ch.id.0);
    }
    if let Some(plane) = &ctx.plane
        && !ids.is_empty()
    {
        plane.channels().refresh().await?;
        plane.wake_supervisor();
    }
    Ok(ids)
}

/// Channels whose verify kind requires secret material the package cannot
/// ship → pending-credentials card.
fn channel_needs_credentials(ch: &crate::integration::channel::ItgChannel) -> bool {
    matches!(
        ch.verify_kind.as_str(),
        "hmac-sha256" | "token" | "jwt" | "wechat-aes" | "challenge"
    ) && ch.credentials.is_none()
}

fn str_field(obj: &serde_json::Map<String, Value>, key: &str) -> String {
    str_field_or(obj, key, "")
}

fn str_field_or(obj: &serde_json::Map<String, Value>, key: &str, default: &str) -> String {
    obj.get(key)
        .and_then(Value::as_str)
        .unwrap_or(default)
        .to_string()
}

fn opt_str_field(obj: &serde_json::Map<String, Value>, key: &str) -> Option<String> {
    obj.get(key)
        .and_then(Value::as_str)
        .map(std::string::ToString::to_string)
}

// ── Step 6: api clients ─────────────────────────────────────────────

async fn step_api_clients(
    ctx: &InstallCtx,
    _target: &InstallTarget,
    pkg: &AppPackage,
    progress: &mut Progress,
    pending: &mut PendingCredentials,
) -> AppResult<()> {
    let empty = serde_json::Map::new();
    for seed in &pkg.api_client_seeds {
        let obj = seed.as_object().unwrap_or(&empty);
        let client_key = str_field(obj, "client_key");
        let now = crate::utils::tz::now_utc();
        let client = crate::integration::api_client::ItgApiClient {
            id: crate::utils::id::new_snowflake_id(),
            tenant_id: crate::constants::DEFAULT_TENANT.to_string(),
            client_key: client_key.clone(),
            display_name: str_field_or(obj, "display_name", &client_key),
            base_url: str_field(obj, "base_url"),
            auth: obj.get("auth").cloned().filter(|v| !v.is_null()),
            credentials: None,
            rate_limit: obj.get("rate_limit").cloned().filter(|v| !v.is_null()),
            ops: obj.get("ops").cloned().filter(|v| !v.is_null()),
            enabled: obj.get("enabled").and_then(Value::as_bool).unwrap_or(true),
            created_at: now,
            updated_at: now,
        };
        let auth_kind = client.auth_kind().to_string();
        crate::integration::api_client::model::insert(&ctx.pool, &client).await?;
        if auth_kind != "none" {
            pending.items.push(format!("api-client:{client_key}"));
        }
        progress
            .commit_inherent(LogStep {
                seq: 0,
                step: "api-clients".to_string(),
                detail: format!("seeded api client '{client_key}'"),
                undo: UndoAction::DeleteApiClient {
                    id: client.id.0.to_string(),
                },
                done: true,
            })
            .await?;
    }
    Ok(())
}

// ── Step 7: seeds ───────────────────────────────────────────────────

async fn step_seeds(
    ctx: &InstallCtx,
    target: &InstallTarget,
    pkg: &AppPackage,
    progress: &mut Progress,
) -> AppResult<()> {
    let schemas: Vec<ContentTypeSchema> =
        pkg.content_types.iter().map(|c| c.schema.clone()).collect();
    let ct_seeds: Vec<(String, Vec<Value>)> = pkg
        .ct_seeds
        .iter()
        .map(|s| (s.table.clone(), s.rows.clone()))
        .collect();
    seeder::run(
        &ctx.pool,
        &target.app_id,
        &pkg.option_seeds,
        &pkg.role_seeds,
        &schemas,
        &ct_seeds,
        progress,
    )
    .await?;
    Ok(())
}

// ── Step 8: admin pages (declaration record — SPA renderer pending) ─

async fn step_admin_pages(pkg: &AppPackage, progress: &mut Progress) -> AppResult<()> {
    progress
        .commit_inherent(LogStep {
            seq: 0,
            step: "admin-pages".to_string(),
            detail: format!(
                "{} admin page declaration(s) recorded (renderer pending)",
                pkg.admin_page_count
            ),
            undo: UndoAction::Noop,
            done: true,
        })
        .await?;
    Ok(())
}
