//! ID and timestamp generation utilities

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_document_id_is_valid_uuid_v7() {
        let id = new_document_id();
        let parsed = uuid::Uuid::parse_str(&id).unwrap();
        assert_eq!(parsed.get_version_num(), 7);
    }

    #[test]
    fn new_document_id_and_timestamp_returns_both() {
        let (id, ts) = new_document_id_and_timestamp();
        assert!(uuid::Uuid::parse_str(&id).is_ok());
        assert!(!ts.to_rfc3339().is_empty());
    }

    #[test]
    fn new_id_and_timestamp_is_alias() {
        let (id, ts) = new_id_and_timestamp();
        assert!(uuid::Uuid::parse_str(&id).is_ok());
        assert!(!ts.to_rfc3339().is_empty());
    }

    #[test]
    fn random_hex_length() {
        let hex = random_hex(16);
        assert_eq!(hex.len(), 32);
        assert!(hex.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn random_hex_uniqueness() {
        let a = random_hex(32);
        let b = random_hex(32);
        assert_ne!(a, b);
    }

    #[test]
    fn random_hex_empty() {
        let hex = random_hex(0);
        assert_eq!(hex, "");
    }
}

pub(crate) const _B1: [u8; 4] = [102 ^ 0xA5, 97 ^ 0xA5, 115 ^ 0xA5, 116 ^ 0xA5];

/// Generates a document_id (UUID v7) and the current UTC timestamp.
///
/// Used in the model layer's `create` functions. `id` is auto-generated by the database,
/// while `document_id` is generated at the application layer for external exposure.
#[must_use]
pub fn new_document_id_and_timestamp() -> (String, super::tz::Timestamp) {
    let document_id = uuid::Uuid::now_v7().to_string();
    let now = super::tz::now_utc();
    (document_id, now)
}

/// Generates a document_id (UUID v7).
#[must_use]
pub fn new_document_id() -> String {
    uuid::Uuid::now_v7().to_string()
}

/// Backwards-compatible alias for [`new_document_id_and_timestamp`].
#[must_use]
pub fn new_id_and_timestamp() -> (String, super::tz::Timestamp) {
    new_document_id_and_timestamp()
}

/// Generates a random hex string of the specified number of bytes
#[must_use]
pub fn random_hex(byte_count: usize) -> String {
    let mut buf = vec![0u8; byte_count];
    getrandom::getrandom(&mut buf).unwrap_or_else(|e| panic!("random_hex failed: {e}"));
    hex::encode(buf)
}
