[content_type]
name = "Docs"
singular = "doc"
plural = "docs"
table = "docs"
implements = ["timestampable"]

[fields.title]
type = "text"
required = true
label = "Title"

[fields.payload]
type = "blob"
label = "Payload"

[fields.gallery]
type = "mediaset"
label = "Gallery"
max_count = 5
